kind: pipeline
name: docker

steps:
  - name: build
    image: plugins/docker
    environment:
      DOCKER_PASSWORD:
        from_secret: my-docker-token
      DOCKER_REGISTRY: https://ghcr.io
      DOCKER_USERNAME: LeKovr
      PLUGIN_TAGS: 0.23,latest
      PLUGIN_REPO: ghcr.io/dopos/narra
