version: '2.1'

services:

  narra-web:
    image: nginx:1.13-alpine
    restart: always
    depends_on:
      - narra-dev
    networks:
      - lan
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${APP_SITE}"
      - "traefik.port=80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./test:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  narra-dev:
    image: narra
    restart: always
    networks:
      - lan
    labels:
      - "traefik.enable=false"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      --as.my_url ${APP_PROTO}://${APP_SITE} --debug
    environment:
      - TYPE=${AS_TYPE}
      - HOST=${AS_HOST}
      - TEAM=${AS_TEAM}
      - CLIENT_ID=${AS_CLIENT_ID}
      - CLIENT_KEY=${AS_CLIENT_KEY}
      - COOKIE_SIGN_KEY=${COOKIE_SIGN_KEY}
      - COOKIE_CRYPT_KEY=${COOKIE_CRYPT_KEY}

    build:
      context: .

networks:
  lan:
    external:
      name: ${DCAPE_NET}

