version: '2.1'

services:

  narra-web:
    image: nginx:1.13-alpine
    restart: always
    depends_on:
      - narra-dev
    networks:
      - lan
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${APP_SITE}"
      - "traefik.port=80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./test:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  narra-dev:
    image: narra
    restart: always
    networks:
      - lan
    labels:
      - "traefik.enable=false"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      --gitea_host ${GITEA_HOST} --cookie_sign ${SIGN_KEY} --cookie_crypt ${CRYPT_KEY}
    build:
      context: .

networks:
  lan:
    external:
      name: ${DCAPE_NET}

