version: '2.1'

services:

  narra-web:
    image: nginx:1.13-alpine
    restart: always
    depends_on:
      - narra-dev
    networks:
      - lan
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.narra-web.rule=Host(`${APP_SITE}`)"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${APP_ROOT}/test:/usr/share/nginx/html:ro
      - ${APP_ROOT}/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  narra-dev:
    image: narra
    restart: always
    networks:
      - lan
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.narra-dev.rule=Host(`${APP_SITE}`) && Path(`/login`,`/auth`,`/401/`)"
      - "traefik.http.services.narra-dev.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.narra-dev.forwardauth.address=http://${APP_SITE}/auth"
      - "traefik.http.middlewares.narra-dev.forwardauth.authResponseHeaders=X-Username"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      --debug --as.my_url ${APP_PROTO}://${APP_SITE}
# For traefik:
# --as.url_header X-Forwarded-Uri  --as.do401 
    environment:
      - AS_TYPE
      - AS_HOST
      - AS_TEAM
      - AS_CLIENT_ID
      - AS_CLIENT_KEY
      - AS_COOKIE_SIGN_KEY
      - AS_COOKIE_CRYPT_KEY
    build:
      context: .

networks:
  lan:
    external:
      name: ${DCAPE_NET}
